openapi: 3.0.3
info:
  title: Foot spec
  description: Foot spec
  version: 1.0.0
servers:
  - url: 'https://petstore3.swagger.io/api/v3'
tags:
  - name: Match
  - name: Player
  - name: Team

paths:
  /matchs:
    get:
      tags:
        - Match
      summary: List of all matchs
      operationId: getAllMatchs
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayAgainst'

        400:
          description: 'BAD REQUEST'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/responses/Bad_request'
  /team:
    get:
      tags:
        - Team
      summary: Get All team and its sponsors and players
      operationId: getAllTeam
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Have'
        400:
          description: 'BAD REQUEST'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/responses/Bad_request'

  /players:
    get:
      tags:
        - Player
      summary: get players
      operationId: getAllPLayers
      responses:
        200:
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        400:
          description: 'BAD REQUEST'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/responses/Bad_request'
components:
  responses:
    Bad_request:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Please verify your request"

  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: 'Leonel Messi'
        position:
          type: string
          example: 'goal keeper'

    Team:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Paris Saint Germain'

    TeamOpponent:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: 'FC Barcelone'

    Sponsor:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Qatar Airways'

    PlayAgainst:
      type: object
      properties:
        id:
          type: integer
          example: 1
        team_id:
          $ref: '#/components/schemas/Team'
        team_opponent_id:
          $ref: '#/components/schemas/TeamOpponent'
        datetime:
          type: string
          format: date

    Have:
      type: object
      properties:
        id:
          type: integer
          example: 10
        team:
          $ref: '#/components/schemas/Team'
        sponsor:
          $ref: '#/components/schemas/Sponsor'
        players:
          $ref: '#/components/schemas/Player'

    Scores:
      type: object
      properties:
        id:
          type: integer
        id_player:
          type: integer
        id_goal:
          type: integer
        scoring_time:
          type: integer

    Goals:
      type: object
      properties:
        id:
          type: integer